// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: fusestream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FuseOp int32

const (
	FuseOp_FUSE_UNKNOWN    FuseOp = 0
	FuseOp_FUSE_STATFS     FuseOp = 1
	FuseOp_FUSE_MKNOD      FuseOp = 2
	FuseOp_FUSE_MKDIR      FuseOp = 3
	FuseOp_FUSE_UNLINK     FuseOp = 4
	FuseOp_FUSE_RMDIR      FuseOp = 5
	FuseOp_FUSE_LINK       FuseOp = 6
	FuseOp_FUSE_SYMLINK    FuseOp = 7
	FuseOp_FUSE_READLINK   FuseOp = 8
	FuseOp_FUSE_RENAME     FuseOp = 9
	FuseOp_FUSE_CHMOD      FuseOp = 10
	FuseOp_FUSE_CHOWN      FuseOp = 11
	FuseOp_FUSE_UTIMENS    FuseOp = 12
	FuseOp_FUSE_CREATE     FuseOp = 13
	FuseOp_FUSE_OPEN       FuseOp = 14
	FuseOp_FUSE_GETATTR    FuseOp = 15
	FuseOp_FUSE_TRUNCATE   FuseOp = 16
	FuseOp_FUSE_READ       FuseOp = 17
	FuseOp_FUSE_WRITE      FuseOp = 18
	FuseOp_FUSE_RELEASE    FuseOp = 19
	FuseOp_FUSE_FSYNC      FuseOp = 20
	FuseOp_FUSE_OPENDIR    FuseOp = 21
	FuseOp_FUSE_READDIR    FuseOp = 22
	FuseOp_FUSE_RELEASEDIR FuseOp = 23
)

// Enum value maps for FuseOp.
var (
	FuseOp_name = map[int32]string{
		0:  "FUSE_UNKNOWN",
		1:  "FUSE_STATFS",
		2:  "FUSE_MKNOD",
		3:  "FUSE_MKDIR",
		4:  "FUSE_UNLINK",
		5:  "FUSE_RMDIR",
		6:  "FUSE_LINK",
		7:  "FUSE_SYMLINK",
		8:  "FUSE_READLINK",
		9:  "FUSE_RENAME",
		10: "FUSE_CHMOD",
		11: "FUSE_CHOWN",
		12: "FUSE_UTIMENS",
		13: "FUSE_CREATE",
		14: "FUSE_OPEN",
		15: "FUSE_GETATTR",
		16: "FUSE_TRUNCATE",
		17: "FUSE_READ",
		18: "FUSE_WRITE",
		19: "FUSE_RELEASE",
		20: "FUSE_FSYNC",
		21: "FUSE_OPENDIR",
		22: "FUSE_READDIR",
		23: "FUSE_RELEASEDIR",
	}
	FuseOp_value = map[string]int32{
		"FUSE_UNKNOWN":    0,
		"FUSE_STATFS":     1,
		"FUSE_MKNOD":      2,
		"FUSE_MKDIR":      3,
		"FUSE_UNLINK":     4,
		"FUSE_RMDIR":      5,
		"FUSE_LINK":       6,
		"FUSE_SYMLINK":    7,
		"FUSE_READLINK":   8,
		"FUSE_RENAME":     9,
		"FUSE_CHMOD":      10,
		"FUSE_CHOWN":      11,
		"FUSE_UTIMENS":    12,
		"FUSE_CREATE":     13,
		"FUSE_OPEN":       14,
		"FUSE_GETATTR":    15,
		"FUSE_TRUNCATE":   16,
		"FUSE_READ":       17,
		"FUSE_WRITE":      18,
		"FUSE_RELEASE":    19,
		"FUSE_FSYNC":      20,
		"FUSE_OPENDIR":    21,
		"FUSE_READDIR":    22,
		"FUSE_RELEASEDIR": 23,
	}
)

func (x FuseOp) Enum() *FuseOp {
	p := new(FuseOp)
	*p = x
	return p
}

func (x FuseOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FuseOp) Descriptor() protoreflect.EnumDescriptor {
	return file_fusestream_proto_enumTypes[0].Descriptor()
}

func (FuseOp) Type() protoreflect.EnumType {
	return &file_fusestream_proto_enumTypes[0]
}

func (x FuseOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FuseOp.Descriptor instead.
func (FuseOp) EnumDescriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{0}
}

type NbdOp int32

const (
	NbdOp_NBD_UNKNOWN NbdOp = 0
	NbdOp_NBD_READAT  NbdOp = 1
	NbdOp_NBD_WRITEAT NbdOp = 2
	NbdOp_NBD_SIZE    NbdOp = 3
	NbdOp_NBD_SYNC    NbdOp = 4
)

// Enum value maps for NbdOp.
var (
	NbdOp_name = map[int32]string{
		0: "NBD_UNKNOWN",
		1: "NBD_READAT",
		2: "NBD_WRITEAT",
		3: "NBD_SIZE",
		4: "NBD_SYNC",
	}
	NbdOp_value = map[string]int32{
		"NBD_UNKNOWN": 0,
		"NBD_READAT":  1,
		"NBD_WRITEAT": 2,
		"NBD_SIZE":    3,
		"NBD_SYNC":    4,
	}
)

func (x NbdOp) Enum() *NbdOp {
	p := new(NbdOp)
	*p = x
	return p
}

func (x NbdOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NbdOp) Descriptor() protoreflect.EnumDescriptor {
	return file_fusestream_proto_enumTypes[1].Descriptor()
}

func (NbdOp) Type() protoreflect.EnumType {
	return &file_fusestream_proto_enumTypes[1]
}

func (x NbdOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NbdOp.Descriptor instead.
func (NbdOp) EnumDescriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{1}
}

type ReturnValueFault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Possibility   float32                `protobuf:"fixed32,1,opt,name=possibility,proto3" json:"possibility,omitempty"`
	ReturnValue   int64                  `protobuf:"varint,2,opt,name=return_value,json=returnValue,proto3" json:"return_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnValueFault) Reset() {
	*x = ReturnValueFault{}
	mi := &file_fusestream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnValueFault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnValueFault) ProtoMessage() {}

func (x *ReturnValueFault) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnValueFault.ProtoReflect.Descriptor instead.
func (*ReturnValueFault) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{0}
}

func (x *ReturnValueFault) GetPossibility() float32 {
	if x != nil {
		return x.Possibility
	}
	return 0
}

func (x *ReturnValueFault) GetReturnValue() int64 {
	if x != nil {
		return x.ReturnValue
	}
	return 0
}

type DelayFault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Possibility   float32                `protobuf:"fixed32,1,opt,name=possibility,proto3" json:"possibility,omitempty"`
	DelayMs       int64                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayFault) Reset() {
	*x = DelayFault{}
	mi := &file_fusestream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayFault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayFault) ProtoMessage() {}

func (x *DelayFault) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayFault.ProtoReflect.Descriptor instead.
func (*DelayFault) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{1}
}

func (x *DelayFault) GetPossibility() float32 {
	if x != nil {
		return x.Possibility
	}
	return 0
}

func (x *DelayFault) GetDelayMs() int64 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type FuseFault struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PathRe string                 `protobuf:"bytes,2,opt,name=path_re,json=pathRe,proto3" json:"path_re,omitempty"`
	Op     FuseOp                 `protobuf:"varint,3,opt,name=op,proto3,enum=slowio.proto.FuseOp" json:"op,omitempty"`
	// Types that are valid to be assigned to ReturnValue:
	//
	//	*FuseFault_ReturnValueFault
	ReturnValue isFuseFault_ReturnValue `protobuf_oneof:"return_value"`
	// Types that are valid to be assigned to Delay:
	//
	//	*FuseFault_DelayFault
	Delay         isFuseFault_Delay `protobuf_oneof:"delay"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuseFault) Reset() {
	*x = FuseFault{}
	mi := &file_fusestream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuseFault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseFault) ProtoMessage() {}

func (x *FuseFault) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseFault.ProtoReflect.Descriptor instead.
func (*FuseFault) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{2}
}

func (x *FuseFault) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FuseFault) GetPathRe() string {
	if x != nil {
		return x.PathRe
	}
	return ""
}

func (x *FuseFault) GetOp() FuseOp {
	if x != nil {
		return x.Op
	}
	return FuseOp_FUSE_UNKNOWN
}

func (x *FuseFault) GetReturnValue() isFuseFault_ReturnValue {
	if x != nil {
		return x.ReturnValue
	}
	return nil
}

func (x *FuseFault) GetReturnValueFault() *ReturnValueFault {
	if x != nil {
		if x, ok := x.ReturnValue.(*FuseFault_ReturnValueFault); ok {
			return x.ReturnValueFault
		}
	}
	return nil
}

func (x *FuseFault) GetDelay() isFuseFault_Delay {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *FuseFault) GetDelayFault() *DelayFault {
	if x != nil {
		if x, ok := x.Delay.(*FuseFault_DelayFault); ok {
			return x.DelayFault
		}
	}
	return nil
}

type isFuseFault_ReturnValue interface {
	isFuseFault_ReturnValue()
}

type FuseFault_ReturnValueFault struct {
	ReturnValueFault *ReturnValueFault `protobuf:"bytes,4,opt,name=return_value_fault,json=returnValueFault,proto3,oneof"`
}

func (*FuseFault_ReturnValueFault) isFuseFault_ReturnValue() {}

type isFuseFault_Delay interface {
	isFuseFault_Delay()
}

type FuseFault_DelayFault struct {
	DelayFault *DelayFault `protobuf:"bytes,5,opt,name=delay_fault,json=delayFault,proto3,oneof"`
}

func (*FuseFault_DelayFault) isFuseFault_Delay() {}

type ErrorFault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Possibility   float32                `protobuf:"fixed32,1,opt,name=possibility,proto3" json:"possibility,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorFault) Reset() {
	*x = ErrorFault{}
	mi := &file_fusestream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorFault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorFault) ProtoMessage() {}

func (x *ErrorFault) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorFault.ProtoReflect.Descriptor instead.
func (*ErrorFault) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorFault) GetPossibility() float32 {
	if x != nil {
		return x.Possibility
	}
	return 0
}

func (x *ErrorFault) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type NbdFault struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Op    NbdOp                  `protobuf:"varint,2,opt,name=op,proto3,enum=slowio.proto.NbdOp" json:"op,omitempty"`
	// Types that are valid to be assigned to PreCond:
	//
	//	*NbdFault_Expression
	PreCond isNbdFault_PreCond `protobuf_oneof:"pre_cond"`
	// Types that are valid to be assigned to ReturnValue:
	//
	//	*NbdFault_ReturnValueFault
	ReturnValue isNbdFault_ReturnValue `protobuf_oneof:"return_value"`
	// Types that are valid to be assigned to Err:
	//
	//	*NbdFault_ErrorFault
	Err isNbdFault_Err `protobuf_oneof:"err"`
	// Types that are valid to be assigned to Delay:
	//
	//	*NbdFault_DelayFault
	Delay         isNbdFault_Delay `protobuf_oneof:"delay"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NbdFault) Reset() {
	*x = NbdFault{}
	mi := &file_fusestream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NbdFault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NbdFault) ProtoMessage() {}

func (x *NbdFault) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NbdFault.ProtoReflect.Descriptor instead.
func (*NbdFault) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{4}
}

func (x *NbdFault) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NbdFault) GetOp() NbdOp {
	if x != nil {
		return x.Op
	}
	return NbdOp_NBD_UNKNOWN
}

func (x *NbdFault) GetPreCond() isNbdFault_PreCond {
	if x != nil {
		return x.PreCond
	}
	return nil
}

func (x *NbdFault) GetExpression() string {
	if x != nil {
		if x, ok := x.PreCond.(*NbdFault_Expression); ok {
			return x.Expression
		}
	}
	return ""
}

func (x *NbdFault) GetReturnValue() isNbdFault_ReturnValue {
	if x != nil {
		return x.ReturnValue
	}
	return nil
}

func (x *NbdFault) GetReturnValueFault() *ReturnValueFault {
	if x != nil {
		if x, ok := x.ReturnValue.(*NbdFault_ReturnValueFault); ok {
			return x.ReturnValueFault
		}
	}
	return nil
}

func (x *NbdFault) GetErr() isNbdFault_Err {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *NbdFault) GetErrorFault() *ErrorFault {
	if x != nil {
		if x, ok := x.Err.(*NbdFault_ErrorFault); ok {
			return x.ErrorFault
		}
	}
	return nil
}

func (x *NbdFault) GetDelay() isNbdFault_Delay {
	if x != nil {
		return x.Delay
	}
	return nil
}

func (x *NbdFault) GetDelayFault() *DelayFault {
	if x != nil {
		if x, ok := x.Delay.(*NbdFault_DelayFault); ok {
			return x.DelayFault
		}
	}
	return nil
}

type isNbdFault_PreCond interface {
	isNbdFault_PreCond()
}

type NbdFault_Expression struct {
	Expression string `protobuf:"bytes,6,opt,name=expression,proto3,oneof"`
}

func (*NbdFault_Expression) isNbdFault_PreCond() {}

type isNbdFault_ReturnValue interface {
	isNbdFault_ReturnValue()
}

type NbdFault_ReturnValueFault struct {
	ReturnValueFault *ReturnValueFault `protobuf:"bytes,3,opt,name=return_value_fault,json=returnValueFault,proto3,oneof"`
}

func (*NbdFault_ReturnValueFault) isNbdFault_ReturnValue() {}

type isNbdFault_Err interface {
	isNbdFault_Err()
}

type NbdFault_ErrorFault struct {
	ErrorFault *ErrorFault `protobuf:"bytes,4,opt,name=error_fault,json=errorFault,proto3,oneof"`
}

func (*NbdFault_ErrorFault) isNbdFault_Err() {}

type isNbdFault_Delay interface {
	isNbdFault_Delay()
}

type NbdFault_DelayFault struct {
	DelayFault *DelayFault `protobuf:"bytes,5,opt,name=delay_fault,json=delayFault,proto3,oneof"`
}

func (*NbdFault_DelayFault) isNbdFault_Delay() {}

type InjectFuseFaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fault         *FuseFault             `protobuf:"bytes,1,opt,name=fault,proto3" json:"fault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFuseFaultRequest) Reset() {
	*x = InjectFuseFaultRequest{}
	mi := &file_fusestream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFuseFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFuseFaultRequest) ProtoMessage() {}

func (x *InjectFuseFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFuseFaultRequest.ProtoReflect.Descriptor instead.
func (*InjectFuseFaultRequest) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{5}
}

func (x *InjectFuseFaultRequest) GetFault() *FuseFault {
	if x != nil {
		return x.Fault
	}
	return nil
}

type InjectFuseFaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectFuseFaultResponse) Reset() {
	*x = InjectFuseFaultResponse{}
	mi := &file_fusestream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectFuseFaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectFuseFaultResponse) ProtoMessage() {}

func (x *InjectFuseFaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectFuseFaultResponse.ProtoReflect.Descriptor instead.
func (*InjectFuseFaultResponse) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{6}
}

func (x *InjectFuseFaultResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InjectNbdFaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fault         *NbdFault              `protobuf:"bytes,1,opt,name=fault,proto3" json:"fault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectNbdFaultRequest) Reset() {
	*x = InjectNbdFaultRequest{}
	mi := &file_fusestream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectNbdFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectNbdFaultRequest) ProtoMessage() {}

func (x *InjectNbdFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectNbdFaultRequest.ProtoReflect.Descriptor instead.
func (*InjectNbdFaultRequest) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{7}
}

func (x *InjectNbdFaultRequest) GetFault() *NbdFault {
	if x != nil {
		return x.Fault
	}
	return nil
}

type InjectNbdFaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectNbdFaultResponse) Reset() {
	*x = InjectNbdFaultResponse{}
	mi := &file_fusestream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectNbdFaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectNbdFaultResponse) ProtoMessage() {}

func (x *InjectNbdFaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectNbdFaultResponse.ProtoReflect.Descriptor instead.
func (*InjectNbdFaultResponse) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{8}
}

func (x *InjectNbdFaultResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int32                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	PathRe        string                 `protobuf:"bytes,2,opt,name=path_re,json=pathRe,proto3" json:"path_re,omitempty"`
	All           bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFaultRequest) Reset() {
	*x = DeleteFaultRequest{}
	mi := &file_fusestream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFaultRequest) ProtoMessage() {}

func (x *DeleteFaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFaultRequest.ProtoReflect.Descriptor instead.
func (*DeleteFaultRequest) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFaultRequest) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DeleteFaultRequest) GetPathRe() string {
	if x != nil {
		return x.PathRe
	}
	return ""
}

func (x *DeleteFaultRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type DeleteFaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedIds    []int32                `protobuf:"varint,1,rep,packed,name=deleted_ids,json=deletedIds,proto3" json:"deleted_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFaultResponse) Reset() {
	*x = DeleteFaultResponse{}
	mi := &file_fusestream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFaultResponse) ProtoMessage() {}

func (x *DeleteFaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFaultResponse.ProtoReflect.Descriptor instead.
func (*DeleteFaultResponse) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteFaultResponse) GetDeletedIds() []int32 {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_fusestream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{11}
}

type ListFaultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FuseFaults    []*FuseFault           `protobuf:"bytes,1,rep,name=fuse_faults,json=fuseFaults,proto3" json:"fuse_faults,omitempty"`
	NbdFaults     []*NbdFault            `protobuf:"bytes,2,rep,name=nbd_faults,json=nbdFaults,proto3" json:"nbd_faults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFaultsResponse) Reset() {
	*x = ListFaultsResponse{}
	mi := &file_fusestream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFaultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFaultsResponse) ProtoMessage() {}

func (x *ListFaultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fusestream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFaultsResponse.ProtoReflect.Descriptor instead.
func (*ListFaultsResponse) Descriptor() ([]byte, []int) {
	return file_fusestream_proto_rawDescGZIP(), []int{12}
}

func (x *ListFaultsResponse) GetFuseFaults() []*FuseFault {
	if x != nil {
		return x.FuseFaults
	}
	return nil
}

func (x *ListFaultsResponse) GetNbdFaults() []*NbdFault {
	if x != nil {
		return x.NbdFaults
	}
	return nil
}

var File_fusestream_proto protoreflect.FileDescriptor

const file_fusestream_proto_rawDesc = "" +
	"\n" +
	"\x10fusestream.proto\x12\fslowio.proto\"W\n" +
	"\x10ReturnValueFault\x12 \n" +
	"\vpossibility\x18\x01 \x01(\x02R\vpossibility\x12!\n" +
	"\freturn_value\x18\x02 \x01(\x03R\vreturnValue\"I\n" +
	"\n" +
	"DelayFault\x12 \n" +
	"\vpossibility\x18\x01 \x01(\x02R\vpossibility\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x03R\adelayMs\"\x80\x02\n" +
	"\tFuseFault\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\apath_re\x18\x02 \x01(\tR\x06pathRe\x12$\n" +
	"\x02op\x18\x03 \x01(\x0e2\x14.slowio.proto.FuseOpR\x02op\x12N\n" +
	"\x12return_value_fault\x18\x04 \x01(\v2\x1e.slowio.proto.ReturnValueFaultH\x00R\x10returnValueFault\x12;\n" +
	"\vdelay_fault\x18\x05 \x01(\v2\x18.slowio.proto.DelayFaultH\x01R\n" +
	"delayFaultB\x0e\n" +
	"\freturn_valueB\a\n" +
	"\x05delay\"@\n" +
	"\n" +
	"ErrorFault\x12 \n" +
	"\vpossibility\x18\x01 \x01(\x02R\vpossibility\x12\x10\n" +
	"\x03err\x18\x02 \x01(\tR\x03err\"\xd7\x02\n" +
	"\bNbdFault\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\x02op\x18\x02 \x01(\x0e2\x13.slowio.proto.NbdOpR\x02op\x12 \n" +
	"\n" +
	"expression\x18\x06 \x01(\tH\x00R\n" +
	"expression\x12N\n" +
	"\x12return_value_fault\x18\x03 \x01(\v2\x1e.slowio.proto.ReturnValueFaultH\x01R\x10returnValueFault\x12;\n" +
	"\verror_fault\x18\x04 \x01(\v2\x18.slowio.proto.ErrorFaultH\x02R\n" +
	"errorFault\x12;\n" +
	"\vdelay_fault\x18\x05 \x01(\v2\x18.slowio.proto.DelayFaultH\x03R\n" +
	"delayFaultB\n" +
	"\n" +
	"\bpre_condB\x0e\n" +
	"\freturn_valueB\x05\n" +
	"\x03errB\a\n" +
	"\x05delay\"G\n" +
	"\x16InjectFuseFaultRequest\x12-\n" +
	"\x05fault\x18\x01 \x01(\v2\x17.slowio.proto.FuseFaultR\x05fault\")\n" +
	"\x17InjectFuseFaultResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"E\n" +
	"\x15InjectNbdFaultRequest\x12,\n" +
	"\x05fault\x18\x01 \x01(\v2\x16.slowio.proto.NbdFaultR\x05fault\"(\n" +
	"\x16InjectNbdFaultResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"O\n" +
	"\x12DeleteFaultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\x12\x17\n" +
	"\apath_re\x18\x02 \x01(\tR\x06pathRe\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\"6\n" +
	"\x13DeleteFaultResponse\x12\x1f\n" +
	"\vdeleted_ids\x18\x01 \x03(\x05R\n" +
	"deletedIds\"\x06\n" +
	"\x04Void\"\x85\x01\n" +
	"\x12ListFaultsResponse\x128\n" +
	"\vfuse_faults\x18\x01 \x03(\v2\x17.slowio.proto.FuseFaultR\n" +
	"fuseFaults\x125\n" +
	"\n" +
	"nbd_faults\x18\x02 \x03(\v2\x16.slowio.proto.NbdFaultR\tnbdFaults*\xa2\x03\n" +
	"\x06FuseOp\x12\x10\n" +
	"\fFUSE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vFUSE_STATFS\x10\x01\x12\x0e\n" +
	"\n" +
	"FUSE_MKNOD\x10\x02\x12\x0e\n" +
	"\n" +
	"FUSE_MKDIR\x10\x03\x12\x0f\n" +
	"\vFUSE_UNLINK\x10\x04\x12\x0e\n" +
	"\n" +
	"FUSE_RMDIR\x10\x05\x12\r\n" +
	"\tFUSE_LINK\x10\x06\x12\x10\n" +
	"\fFUSE_SYMLINK\x10\a\x12\x11\n" +
	"\rFUSE_READLINK\x10\b\x12\x0f\n" +
	"\vFUSE_RENAME\x10\t\x12\x0e\n" +
	"\n" +
	"FUSE_CHMOD\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"FUSE_CHOWN\x10\v\x12\x10\n" +
	"\fFUSE_UTIMENS\x10\f\x12\x0f\n" +
	"\vFUSE_CREATE\x10\r\x12\r\n" +
	"\tFUSE_OPEN\x10\x0e\x12\x10\n" +
	"\fFUSE_GETATTR\x10\x0f\x12\x11\n" +
	"\rFUSE_TRUNCATE\x10\x10\x12\r\n" +
	"\tFUSE_READ\x10\x11\x12\x0e\n" +
	"\n" +
	"FUSE_WRITE\x10\x12\x12\x10\n" +
	"\fFUSE_RELEASE\x10\x13\x12\x0e\n" +
	"\n" +
	"FUSE_FSYNC\x10\x14\x12\x10\n" +
	"\fFUSE_OPENDIR\x10\x15\x12\x10\n" +
	"\fFUSE_READDIR\x10\x16\x12\x13\n" +
	"\x0fFUSE_RELEASEDIR\x10\x17*U\n" +
	"\x05NbdOp\x12\x0f\n" +
	"\vNBD_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"NBD_READAT\x10\x01\x12\x0f\n" +
	"\vNBD_WRITEAT\x10\x02\x12\f\n" +
	"\bNBD_SIZE\x10\x03\x12\f\n" +
	"\bNBD_SYNC\x10\x042\xe1\x02\n" +
	"\n" +
	"FuseStream\x12B\n" +
	"\n" +
	"ListFaults\x12\x12.slowio.proto.Void\x1a .slowio.proto.ListFaultsResponse\x12R\n" +
	"\vDeleteFault\x12 .slowio.proto.DeleteFaultRequest\x1a!.slowio.proto.DeleteFaultResponse\x12^\n" +
	"\x0fInjectFuseFault\x12$.slowio.proto.InjectFuseFaultRequest\x1a%.slowio.proto.InjectFuseFaultResponse\x12[\n" +
	"\x0eInjectNbdFault\x12#.slowio.proto.InjectNbdFaultRequest\x1a$.slowio.proto.InjectNbdFaultResponseB$Z\"github.com/fanyang89/fusestream/pbb\x06proto3"

var (
	file_fusestream_proto_rawDescOnce sync.Once
	file_fusestream_proto_rawDescData []byte
)

func file_fusestream_proto_rawDescGZIP() []byte {
	file_fusestream_proto_rawDescOnce.Do(func() {
		file_fusestream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fusestream_proto_rawDesc), len(file_fusestream_proto_rawDesc)))
	})
	return file_fusestream_proto_rawDescData
}

var file_fusestream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fusestream_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_fusestream_proto_goTypes = []any{
	(FuseOp)(0),                     // 0: slowio.proto.FuseOp
	(NbdOp)(0),                      // 1: slowio.proto.NbdOp
	(*ReturnValueFault)(nil),        // 2: slowio.proto.ReturnValueFault
	(*DelayFault)(nil),              // 3: slowio.proto.DelayFault
	(*FuseFault)(nil),               // 4: slowio.proto.FuseFault
	(*ErrorFault)(nil),              // 5: slowio.proto.ErrorFault
	(*NbdFault)(nil),                // 6: slowio.proto.NbdFault
	(*InjectFuseFaultRequest)(nil),  // 7: slowio.proto.InjectFuseFaultRequest
	(*InjectFuseFaultResponse)(nil), // 8: slowio.proto.InjectFuseFaultResponse
	(*InjectNbdFaultRequest)(nil),   // 9: slowio.proto.InjectNbdFaultRequest
	(*InjectNbdFaultResponse)(nil),  // 10: slowio.proto.InjectNbdFaultResponse
	(*DeleteFaultRequest)(nil),      // 11: slowio.proto.DeleteFaultRequest
	(*DeleteFaultResponse)(nil),     // 12: slowio.proto.DeleteFaultResponse
	(*Void)(nil),                    // 13: slowio.proto.Void
	(*ListFaultsResponse)(nil),      // 14: slowio.proto.ListFaultsResponse
}
var file_fusestream_proto_depIdxs = []int32{
	0,  // 0: slowio.proto.FuseFault.op:type_name -> slowio.proto.FuseOp
	2,  // 1: slowio.proto.FuseFault.return_value_fault:type_name -> slowio.proto.ReturnValueFault
	3,  // 2: slowio.proto.FuseFault.delay_fault:type_name -> slowio.proto.DelayFault
	1,  // 3: slowio.proto.NbdFault.op:type_name -> slowio.proto.NbdOp
	2,  // 4: slowio.proto.NbdFault.return_value_fault:type_name -> slowio.proto.ReturnValueFault
	5,  // 5: slowio.proto.NbdFault.error_fault:type_name -> slowio.proto.ErrorFault
	3,  // 6: slowio.proto.NbdFault.delay_fault:type_name -> slowio.proto.DelayFault
	4,  // 7: slowio.proto.InjectFuseFaultRequest.fault:type_name -> slowio.proto.FuseFault
	6,  // 8: slowio.proto.InjectNbdFaultRequest.fault:type_name -> slowio.proto.NbdFault
	4,  // 9: slowio.proto.ListFaultsResponse.fuse_faults:type_name -> slowio.proto.FuseFault
	6,  // 10: slowio.proto.ListFaultsResponse.nbd_faults:type_name -> slowio.proto.NbdFault
	13, // 11: slowio.proto.FuseStream.ListFaults:input_type -> slowio.proto.Void
	11, // 12: slowio.proto.FuseStream.DeleteFault:input_type -> slowio.proto.DeleteFaultRequest
	7,  // 13: slowio.proto.FuseStream.InjectFuseFault:input_type -> slowio.proto.InjectFuseFaultRequest
	9,  // 14: slowio.proto.FuseStream.InjectNbdFault:input_type -> slowio.proto.InjectNbdFaultRequest
	14, // 15: slowio.proto.FuseStream.ListFaults:output_type -> slowio.proto.ListFaultsResponse
	12, // 16: slowio.proto.FuseStream.DeleteFault:output_type -> slowio.proto.DeleteFaultResponse
	8,  // 17: slowio.proto.FuseStream.InjectFuseFault:output_type -> slowio.proto.InjectFuseFaultResponse
	10, // 18: slowio.proto.FuseStream.InjectNbdFault:output_type -> slowio.proto.InjectNbdFaultResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_fusestream_proto_init() }
func file_fusestream_proto_init() {
	if File_fusestream_proto != nil {
		return
	}
	file_fusestream_proto_msgTypes[2].OneofWrappers = []any{
		(*FuseFault_ReturnValueFault)(nil),
		(*FuseFault_DelayFault)(nil),
	}
	file_fusestream_proto_msgTypes[4].OneofWrappers = []any{
		(*NbdFault_Expression)(nil),
		(*NbdFault_ReturnValueFault)(nil),
		(*NbdFault_ErrorFault)(nil),
		(*NbdFault_DelayFault)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fusestream_proto_rawDesc), len(file_fusestream_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fusestream_proto_goTypes,
		DependencyIndexes: file_fusestream_proto_depIdxs,
		EnumInfos:         file_fusestream_proto_enumTypes,
		MessageInfos:      file_fusestream_proto_msgTypes,
	}.Build()
	File_fusestream_proto = out.File
	file_fusestream_proto_goTypes = nil
	file_fusestream_proto_depIdxs = nil
}
