// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: fusestream.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FuseStream_ListFaults_FullMethodName      = "/slowio.proto.FuseStream/ListFaults"
	FuseStream_DeleteFault_FullMethodName     = "/slowio.proto.FuseStream/DeleteFault"
	FuseStream_InjectFuseFault_FullMethodName = "/slowio.proto.FuseStream/InjectFuseFault"
	FuseStream_InjectNbdFault_FullMethodName  = "/slowio.proto.FuseStream/InjectNbdFault"
)

// FuseStreamClient is the client API for FuseStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FuseStreamClient interface {
	ListFaults(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ListFaultsResponse, error)
	DeleteFault(ctx context.Context, in *DeleteFaultRequest, opts ...grpc.CallOption) (*DeleteFaultResponse, error)
	InjectFuseFault(ctx context.Context, in *InjectFuseFaultRequest, opts ...grpc.CallOption) (*InjectFuseFaultResponse, error)
	InjectNbdFault(ctx context.Context, in *InjectNbdFaultRequest, opts ...grpc.CallOption) (*InjectNbdFaultResponse, error)
}

type fuseStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewFuseStreamClient(cc grpc.ClientConnInterface) FuseStreamClient {
	return &fuseStreamClient{cc}
}

func (c *fuseStreamClient) ListFaults(ctx context.Context, in *Void, opts ...grpc.CallOption) (*ListFaultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFaultsResponse)
	err := c.cc.Invoke(ctx, FuseStream_ListFaults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fuseStreamClient) DeleteFault(ctx context.Context, in *DeleteFaultRequest, opts ...grpc.CallOption) (*DeleteFaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFaultResponse)
	err := c.cc.Invoke(ctx, FuseStream_DeleteFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fuseStreamClient) InjectFuseFault(ctx context.Context, in *InjectFuseFaultRequest, opts ...grpc.CallOption) (*InjectFuseFaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectFuseFaultResponse)
	err := c.cc.Invoke(ctx, FuseStream_InjectFuseFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fuseStreamClient) InjectNbdFault(ctx context.Context, in *InjectNbdFaultRequest, opts ...grpc.CallOption) (*InjectNbdFaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectNbdFaultResponse)
	err := c.cc.Invoke(ctx, FuseStream_InjectNbdFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FuseStreamServer is the server API for FuseStream service.
// All implementations must embed UnimplementedFuseStreamServer
// for forward compatibility.
type FuseStreamServer interface {
	ListFaults(context.Context, *Void) (*ListFaultsResponse, error)
	DeleteFault(context.Context, *DeleteFaultRequest) (*DeleteFaultResponse, error)
	InjectFuseFault(context.Context, *InjectFuseFaultRequest) (*InjectFuseFaultResponse, error)
	InjectNbdFault(context.Context, *InjectNbdFaultRequest) (*InjectNbdFaultResponse, error)
	mustEmbedUnimplementedFuseStreamServer()
}

// UnimplementedFuseStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFuseStreamServer struct{}

func (UnimplementedFuseStreamServer) ListFaults(context.Context, *Void) (*ListFaultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFaults not implemented")
}
func (UnimplementedFuseStreamServer) DeleteFault(context.Context, *DeleteFaultRequest) (*DeleteFaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFault not implemented")
}
func (UnimplementedFuseStreamServer) InjectFuseFault(context.Context, *InjectFuseFaultRequest) (*InjectFuseFaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectFuseFault not implemented")
}
func (UnimplementedFuseStreamServer) InjectNbdFault(context.Context, *InjectNbdFaultRequest) (*InjectNbdFaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InjectNbdFault not implemented")
}
func (UnimplementedFuseStreamServer) mustEmbedUnimplementedFuseStreamServer() {}
func (UnimplementedFuseStreamServer) testEmbeddedByValue()                    {}

// UnsafeFuseStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FuseStreamServer will
// result in compilation errors.
type UnsafeFuseStreamServer interface {
	mustEmbedUnimplementedFuseStreamServer()
}

func RegisterFuseStreamServer(s grpc.ServiceRegistrar, srv FuseStreamServer) {
	// If the following call pancis, it indicates UnimplementedFuseStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FuseStream_ServiceDesc, srv)
}

func _FuseStream_ListFaults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuseStreamServer).ListFaults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FuseStream_ListFaults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuseStreamServer).ListFaults(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _FuseStream_DeleteFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuseStreamServer).DeleteFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FuseStream_DeleteFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuseStreamServer).DeleteFault(ctx, req.(*DeleteFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FuseStream_InjectFuseFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectFuseFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuseStreamServer).InjectFuseFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FuseStream_InjectFuseFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuseStreamServer).InjectFuseFault(ctx, req.(*InjectFuseFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FuseStream_InjectNbdFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectNbdFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuseStreamServer).InjectNbdFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FuseStream_InjectNbdFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuseStreamServer).InjectNbdFault(ctx, req.(*InjectNbdFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FuseStream_ServiceDesc is the grpc.ServiceDesc for FuseStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FuseStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "slowio.proto.FuseStream",
	HandlerType: (*FuseStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFaults",
			Handler:    _FuseStream_ListFaults_Handler,
		},
		{
			MethodName: "DeleteFault",
			Handler:    _FuseStream_DeleteFault_Handler,
		},
		{
			MethodName: "InjectFuseFault",
			Handler:    _FuseStream_InjectFuseFault_Handler,
		},
		{
			MethodName: "InjectNbdFault",
			Handler:    _FuseStream_InjectNbdFault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fusestream.proto",
}
